function result = ...
    cluster_head_energy_dissipating(i,available_node_set,d0_square,signal_bit,Eelec,EDA,Efs,Emp,node,sink)
distance_square = ...
    ( node(available_node_set(i)).xd - sink.xd )^2 + ( node(available_node_set(i)).yd - sink.yd )^2;
if distance_square <= d0_square
    node(available_node_set(i)).energy = ...
        node(available_node_set(i)).energy - signal_bit * (Eelec * node(available_node_set(i)).member_amount + EDA * node(available_node_set(i)).member_amount + Efs * distance_square);
else
    node(available_node_set(i)).energy = ...
        node(available_node_set(i)).energy - signal_bit * (Eelec * node(available_node_set(i)).member_amount + EDA * node(available_node_set(i)).member_amount + Emp * (distance_square)^2);
end
result = node;