function node_ploting(i,node)
if node(i).energy <= 0
    % 死亡节点
    plot(node(i).xd,node(i).yd,'r.',...
        'LineWidth',2,...
        'MarkerSize',13);
    return
end

if strcmp(node(i).type,'AD')
    % advanced node
    plot(node(i).xd,node(i).yd,'+',...
        'LineWidth',1,...
        'MarkerEdgeColor','b',...
        'MarkerSize',7);
elseif strcmp(node(i).type,'N')
    % 正常节点
    plot(node(i).xd,node(i).yd,'o',...
        'LineWidth',1,...
        'MarkerEdgeColor','k',...
        'MarkerSize',7);
end