function result = snapshot_data_saving(xn_dim,r,n,node,xn,sink)
temp_vector = zeros(n,1);
snapshot = dataset(temp_vector,...
    temp_vector,...
    temp_vector,...
    cell(n,1),...
    temp_vector,...
    temp_vector,...
    zeros(n,xn_dim + 1),...
    'VarNames',{'xd' 'yd' 'energy' 'type'...
    'cluster_number' 'Group_N_CH' 'info'});
for i = 1:n
    snapshot.xd(i) = node(i).xd;
    snapshot.yd(i) = node(i).yd;
    snapshot.energy(i) = node(i).energy;
    snapshot.type(i) = {node(i).type};
    snapshot.cluster_number(i) = node(i).cluster_number;
    snapshot.Group_N_CH(i) = node(i).Group_N_CH;
    snapshot.info(i,:) = node(i).info;
end

% ±£´æÊý¾Ý
data_name = ...
    sprintf('round %d.mat',r);
save(data_name,'snapshot','node','xn','sink')
result = snapshot;